added apis for tenant creation and deletion
Click2Cloud-Centaurus/dashboard pull request #3
Opened 2021-11-29 06:23 UTC by click2cloud-team3

2021-11-29 06:27 UTC, click2cloud-amit approved these changes, later dismissed
/lgtm

2021-11-30 05:56 UTC, Click2Cloud-rninja requested changes

2021-11-30 05:56 UTC, Click2Cloud-rninja commented on src/app/backend/handler/apihandler.go
> +	if err := tenant.DeleteTenant(tenantSpec, k8sClient); err != nil {
Do we need tenantSpec? we can pass just tenant name in DeleteTenant function.

```
if err := tenant.DeleteTenant(tenant_name, k8sClient); err != nil {
```

2021-11-30 05:56 UTC, Click2Cloud-rninja commented on src/app/backend/handler/apihandler.go
> +		log.Printf("Deleting Tenant %s", tenant_name)
Delete this log

2021-11-30 05:56 UTC, Click2Cloud-rninja commented on src/app/backend/resource/tenant/common.go
> +	StorageClusterId string `json:"storageclusterid"`
Add description for StorageClusterId

2021-11-30 05:56 UTC, Click2Cloud-rninja commented on src/app/backend/resource/tenant/common.go
> +func DeleteTenant(spec *TenantSpec, client kubernetes.Interface) error {
instead of spec(tenantSpec), we can use simple string like `tenantName string`

2021-11-30 05:56 UTC, Click2Cloud-rninja commented on src/app/backend/resource/tenant/common.go
> +	if err != nil {
this `if` portion is not required

2021-11-30 05:56 UTC, Click2Cloud-rninja commented on src/app/backend/resource/tenant/common.go
> +
remove extra spaces/lines

2021-11-30 06:42 UTC, click2cloud-team3 commented on src/app/backend/handler/apihandler.go
> +	if err := tenant.DeleteTenant(tenantSpec, k8sClient); err != nil {
Made changes as per suggestions, Thank you

2021-11-30 06:42 UTC, click2cloud-team3 commented on src/app/backend/handler/apihandler.go
> +		log.Printf("Deleting Tenant %s", tenant_name)
Deleted the log statement, Thank you.

2021-11-30 06:43 UTC, click2cloud-team3 commented on src/app/backend/resource/tenant/common.go
> +	StorageClusterId string `json:"storageclusterid"`
Added description for StorageClusterId. Thank you.

2021-11-30 06:44 UTC, click2cloud-team3 commented on src/app/backend/resource/tenant/common.go
> +func DeleteTenant(spec *TenantSpec, client kubernetes.Interface) error {
Changes Implemented as per suggestion. Thanks

2021-11-30 06:45 UTC, click2cloud-team3 commented on src/app/backend/resource/tenant/common.go
> +	if err != nil {
Removed the conditional portion. Thanks

2021-11-30 06:46 UTC, click2cloud-team3 commented on src/app/backend/resource/tenant/common.go
> +
Removed the extra spaces/lines. Thank you @Click2Cloud-rninja

2021-11-30 08:54 UTC, click2cloud-amit approved these changes
/lgtm

2021-11-30 12:48 UTC, merged

2021-12-01 05:24 UTC, Click2Cloud-rninja reviewed
/lgtm